
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  db:
    image: mongo:8.0
    volumes:
      - spotify-data:/data/db
    ports:
      - "27017:27017"

volumes:
  spotify-data:

